- name: Deploy Functions
  env:
    GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  run: |
    echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcloud.json
    export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
    firebase deploy --only functions --project gillythekid-c6c48
